$ANSIBLE_VAULT;1.1;AES256
39376435623436386237613165646562313332636565333565323131386561666266353639346137
3163346136336636613130366262636637356537643839300a613834623065613039643964356463
31346137363335313739616366633532356431373831356532633532643233316532653139666662
6530343464356431330a363830326634663639613139313665306134333939643038656261366661
62303238343563363334633536353335373238353663306265373765393065303936333865616265
37343738633734313332363637623032333632363361353230313838646136363839666330373262
30323962613261303863333362343638346333386263343935313736396133346664663831363635
39373765363936616637626531383436336635666239363664353638623262643161336233393638
35636637616561373865333532636538313431306563393131383434336635386337
